services:
  api:
    build: .
    ports:
      - "3030:${PORT:-80}"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_HOST: db

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-apiresultsrootpwd}
      MYSQL_DATABASE: ${DB_NAME:-cesi_live_quizz}
      MYSQL_USER: ${DB_USER:-apiresultsuser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-apiresultspwd}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_DB_HOST: db
      ADMINER_DEFAULT_DB_PORT: ${DB_PORT:-3306}
      ADMINER_DEFAULT_DB_USERNAME: ${DB_USER:-apiresultsuser}
      ADMINER_DEFAULT_DB_PASSWORD: ${DB_PASSWORD:-apiresultspwd}
      ADMINER_DEFAULT_DB_NAME: ${DB_NAME:-cesi_live_quizz}
    depends_on:
      - db

volumes:
  db_data: {}
